### ISSUE TITLE
The AI in the solution branch is beatable

### ISSUE THREAD

**Issue by morgvanny** [learn-co-students/ttt-with-ai-project-v-000#52]
It runs on the assumption that a corner is always better than a side, if a side is neither winning nor blocking a win. This isn't the case. If X takes a corner, O has to take middle, and then if X takes the opposite corner, O has to take a side, or it loses. If it takes one of the remaining corners, X will block, and simultaneously set up 2 ways to win.

There should be an exception where the computer won't take a corner in this situation. As far as I can tell, there are no other exceptions, so it should be a sound strategy at that point.

**Comment by randallreedjr** [comment]
@morgvanny I just saw your issue, well done! I will work on a pull request for this (if one doesn't already exist).

**Comment by gj** [comment]
This can be closed @pletcher
